name: cardiogram
description: "monitor your heart rate with this"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  action_slider: ^0.7.0
  animate_do: ^3.3.1
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  emailjs: ^1.1.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firebase_service: ^0.0.1+1
  fl_chart: ^0.66.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.2.1
  iconsax: ^0.0.8
  intl: ^0.19.0
  provider: null
  slide_to_act: ^2.0.2
  syncfusion_flutter_charts: ^24.1.47+2
  twilio_flutter: ^0.0.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
